<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Idpuwu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Idpuwu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6Idpuwu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6Idpuwu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6Idpuwu\App_KernelDevDebugContainer([
    'container.build_hash' => '6Idpuwu',
    'container.build_id' => '94c3eaf8',
    'container.build_time' => 1672764931,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Idpuwu');
